### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by Rukongai** [RulHolos/Bartender#13]
Hey I think it would be crazy helpful to be able to use some predefined variables in barload commands

My specific use-case would be using something like [class] to parse the players current class/job to cut down on my macro usage. Right now I have macros for loading different bars and it'd be nice to replace them all with 1 or 2 macros that looks like

```
/barload [class]-singletarget
/barload [class]-multitarget
/barload [class]-cd
```

etc

**Comment by RulHolos** [comment]
Added in 068ca98
