### ISSUE TITLE
[Feature] Level in Automation

### ISSUE THREAD

**Issue by shimmer-n-shine** [RulHolos/Bartender#23]
Hi! It would be wonderful if Bartender allowed you to use the current level of your job in automation. e.g. having a hotbar only activate if you're playing Astrologian synced to level 0-25, 25-50, 50-75, 75-100.

As you know, some job actions become obsolete for some jobs as they get higher in level (e.g benefic 1), and some jobs have their core rotations change once they hit specific milestones (e.g black mage).

**Comment by RulHolos** [comment]
Added in d6c7ffa in the form of two conditions:
Level higher than ...
Level lower than ...

They're level inclusive.
